name: Deploy sito statico

on:
  push:
    branches:
      - main  # o 'master', dipende dal tuo repo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del codice
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build del sito (opzionale)
        run: |
          npm install
          npm run build

      - name: Deploy su GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # o ./build, ./public, ecc.
